name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

env:
  PIP_CACHE_DIR: ${{ github.workspace }}/.cache/pip

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 isort black mypy pytest

      - name: Run flake8
        run: flake8 .

      - name: Run isort check
        run: isort --check-only .

      - name: Run black check
        run: black --check .

      - name: Run mypy
        run: mypy .

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest tests

